### ISSUE TITLE
Dependencies are not manager by setup

### ISSUE THREAD

**Issue by titom73** [titom73/inetsix-python-lib#2]
After publishing module, `pip install` does not manage dependencies:

```shell
$ pip install inetsix
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting inetsix
  Using cached https://files.pythonhosted.org/packages/c5/86/6902e08fb22e278e267ab056cb8daa1c4a2d92bf8e57907c9a3aaf40ade5/inetsix-0.0.1rc0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bj/x0pdlg4s46vbk9t8916xkfb00000gn/T/pip-install-4fVAth/inetsix/setup.py", line 2, in <module>
        import inetsix
      File "inetsix/__init__.py", line 18, in <module>
        import colorful
    ImportError: No module named colorful
```

**Comment by titom73** [comment]
Merged in MR#3
